/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGAS;

import java.text.NumberFormat;
import java.util.Locale;
import java.util.StringTokenizer;

public class TOKO extends javax.swing.JFrame {
    
    public StringTokenizer token;
    public String gantiformat="";
    public String nm_barang="";
    public long harga_brg;
    public int jml_beli;
    public long jumlah_hrg;
    public long kembalian;
    public long jumlahbyr;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TOKO.class.getName());

    /**
     * Creates new form TOKO
     */
    public TOKO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TxtHargaBarang = new javax.swing.JTextField();
        TxtJBeli = new javax.swing.JTextField();
        TxtJmlHarga = new javax.swing.JTextField();
        TxtJmlBayar = new javax.swing.JTextField();
        TxtJmlKembalian = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAMA BARANG");

        jLabel2.setText("HARGA BARANG");

        jLabel3.setText("JUMLAH BELI");

        jLabel4.setText("JUMLAH HARGA");

        jLabel5.setText("JUMLAH BAYAR");

        jLabel6.setText("JUMLAH KEMBALIAN");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TELEVISI", "SPEAKER", "KULKAS", "" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        TxtHargaBarang.addActionListener(this::TxtHargaBarangActionPerformed);

        TxtJmlHarga.addActionListener(this::TxtJmlHargaActionPerformed);

        TxtJmlBayar.addActionListener(this::TxtJmlBayarActionPerformed);

        jButton1.setText("BATAL");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("KELUAR");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("HITUNG JUMLAH HARGA");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtHargaBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(TxtJBeli)
                    .addComponent(TxtJmlHarga)
                    .addComponent(TxtJmlBayar)
                    .addComponent(TxtJmlKembalian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TxtHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(TxtJBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(TxtJmlHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtJmlBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtJmlKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        nm_barang=(String)jComboBox1.getSelectedItem();
        
        if(nm_barang=="TELEVISI")
        {
            harga_brg=2500000;
        }else if(nm_barang=="SPEAKER")
        {
            harga_brg=1250000;
        }else if(nm_barang=="KULKAS")
        {
            harga_brg=2800000;
        }
        
        gantiformat=NumberFormat.getNumberInstance(Locale.ENGLISH).format(harga_brg);
        token=new StringTokenizer(gantiformat,".");
        gantiformat=token.nextToken();
        gantiformat=gantiformat.replace(",","");
        TxtHargaBarang.setText(gantiformat);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TxtHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtHargaBarangActionPerformed

    private void TxtJmlHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJmlHargaActionPerformed
         try {
        String namaBarang = jComboBox1.getSelectedItem().toString();
        int harga = Integer.parseInt(TxtHargaBarang.getText());
        int jumlah = Integer.parseInt(TxtJBeli.getText());

        int total = harga * jumlah;
        TxtJBeli.setText(String.valueOf(total));

        int bayar = Integer.parseInt(TxtJmlBayar.getText());
        int kembalian = bayar - total;
        TxtJmlKembalian.setText(String.valueOf(kembalian));

        jTextArea1.setText(
            "===== STRUK PEMBELIAN =====\n" +
            "Nama Barang : " + namaBarang + "\n" +
            "Harga       : Rp " + harga + "\n" +
            "Jumlah Beli : " + jumlah + "\n" +
            "---------------------------\n" +
            "Total Harga : Rp " + total + "\n" +
            "Bayar       : Rp " + bayar + "\n" +
            "Kembalian   : Rp " + kembalian + "\n" +
            "===========================\n" +
            "Terima kasih!"
        );

    } catch (Exception e) {
        jTextArea1.setText("Input tidak valid!");
    }
    }//GEN-LAST:event_TxtJmlHargaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jml_beli=Integer.parseInt(TxtJBeli.getText());
        
        jumlah_hrg=jml_beli*harga_brg;
        
        gantiformat=NumberFormat.getNumberInstance(Locale.ENGLISH).format(jumlah_hrg);
        token=new StringTokenizer(gantiformat,".");
        gantiformat=token.nextToken();
        gantiformat=gantiformat.replace(",","");
        TxtJmlHarga.setText(gantiformat);
        
        // 🔥 TAMBAHKAN INI (STRUK)
        try {
    int harga = Integer.parseInt(TxtJmlHarga.getText().replace(".", ""));
    int jumlah = Integer.parseInt(TxtJBeli.getText());
    int bayar = Integer.parseInt(TxtJmlBayar.getText().replace(".", ""));
    int total = harga * jumlah;
    int kembalian = bayar - total;

    // Format kembali ke rupiah
    NumberFormat nf = NumberFormat.getInstance(Locale.ENGLISH);

    TxtJmlHarga.setText(nf.format(total).replace(",", "."));
    TxtJmlKembalian.setText(nf.format(kembalian).replace(",", "."));


    String namaBarang = jComboBox1.getSelectedItem().toString();

    jTextArea1.setText(
        "===== STRUK PEMBELIAN =====\n" +
        "Nama Barang : " + namaBarang + "\n" +
        "Harga       : Rp " + nf.format(harga).replace(",", ".") + "\n" +
        "Jumlah Beli : " + jumlah + "\n" +
        "---------------------------\n" +
        "Total Harga : Rp " + nf.format(total).replace(",", ".") + "\n" +
        "Bayar       : Rp " + nf.format(bayar).replace(",", ".") + "\n" +
        "Kembalian   : Rp " + nf.format(kembalian).replace(",", ".") + "\n" +
        "===========================\n" +
        "Terima kasih! Telah Berbelanja"
    );

} catch (Exception e) {
    jTextArea1.setText("Terjadi kesalahan input!");
}
    

    }//GEN-LAST:event_jButton3ActionPerformed

    private void TxtJmlBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJmlBayarActionPerformed
        jumlahbyr=Long.parseLong(TxtJmlBayar.getText());
        
        kembalian=jumlahbyr-jumlah_hrg;
        
        gantiformat=NumberFormat.getNumberInstance(Locale.ENGLISH).format(jumlahbyr);
        token=new StringTokenizer(gantiformat,".");
        gantiformat=token.nextToken();
        gantiformat=gantiformat.replace(",","");
        TxtJmlBayar.setText(gantiformat);
        
        gantiformat=NumberFormat.getNumberInstance(Locale.ENGLISH).format(kembalian);
        token=new StringTokenizer(gantiformat,".");
        gantiformat=token.nextToken();
        gantiformat=gantiformat.replace(",","");
        TxtJmlKembalian.setText(gantiformat);
    }//GEN-LAST:event_TxtJmlBayarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          jComboBox1.setSelectedIndex(-1);
       TxtHargaBarang.setText("");
       TxtJBeli.setText("");
       TxtJmlBayar.setText("");
       TxtJmlHarga.setText("");
       TxtJmlKembalian.setText("");
       jTextArea1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   
    System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TOKO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtHargaBarang;
    private javax.swing.JTextField TxtJBeli;
    private javax.swing.JTextField TxtJmlBayar;
    private javax.swing.JTextField TxtJmlHarga;
    private javax.swing.JTextField TxtJmlKembalian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

   
}
